board: sofle
# Adjust key sizing for better text accommodation
draw_config:
  key_h: 70 # Increase height of keys (default is 60)
  key_w: 60 # Increase width of keys (default is 50-60)
  split_gap: 30 # Gap between split halves
  combo_h: 25 # Height of combo lines
  key_rx: 6 # Corner radius
  key_ry: 6

  # Enable combo visualization
  combo_w: 3 # Width of combo lines
  combo_opacity: 0.75 # Opacity of combo lines
  draw_combos: true # Enable combo visualization

  # Optional: Improve text display
  legend_fontsize: 14 # Increase font size (default is 12)
  legend_hjustify: 0.5 # Center horizontally
  legend_vjustify: 0.5 # Center vertically

  # Visual styling
  keycap_margin: 3 # Margin between keycaps
  line_width: 2 # Border thickness
  inner_pad_h: 2 # Inner padding for each key (horizontal)
  inner_pad_v: 2 # Inner padding for each key (vertical)

  # Adjust tap/hold text layout
  # For Combos/Tap-hold/Shifted legends
  tap_hjustify: 0.5
  tap_vjustify: 0.2 # Place tap legends higher in the key
  hold_hjustify: 0.5
  hold_vjustify: 0.8 # Place hold legends lower in the key

# Configuration for keymap-drawer

# Key size and position settings
key_h: 70 # Height of keys
key_w: 60 # Width of keys
key_rx: 6 # Corner radius
key_ry: 6

# Enable combo visualization
combo_w: 3 # Width of combo lines
combo_opacity: 0.75 # Opacity of combo lines
draw_combos: true # Enable combo visualization

# Text display settings
legend_fontsize: 14 # Font size for the legends
sub_fontsize: 8 # Font size for the small labels
tt_fmt_hint: '⌘ %s' # Format for tap-term labels
tt_rect: true # Show label outline
gap_h: 20 # Horizontal gap between key columns
gap_v: 20 # Vertical gap between key rows

# Border and margin settings
margin_h: 20
margin_v: 20
line_color: '#888888' # Border color
line_width: 2 # Border thickness
inner_pad_h: 2 # Inner padding for each key (horizontal)
inner_pad_v: 2 # Inner padding for each key (vertical)

# Adjust tap/hold text layout
combo_h_padding: 2 # Horizontal padding for tap/hold positions
combo_v_padding: 2 # Vertical padding for tap/hold positions

# Position of tap text (center-aligned by default)
tap_position:
  x: 0
  y: 0
  # anchor: "center" # Default text anchor

# Position of hold text (top-right by default)
hold_position:
  x: 20
  y: -18
  # anchor: "end" # Default text anchor
